Add system tests
Hydrospheredata/hydro-serving pull request #337
Opened 2020-11-27 14:14 UTC by BeardedWhale

2020-11-27 19:12 UTC, akastav commented on .tests/Dockerfile
> +RUN hs cluster use $CLUSTER_NAME
in the process of building the container, you immediately generate a config for hs and there will always be localhost: 80, if you run such a container, it is useless to redefine env. 
So I added buildargs. 
If you want it to work, you need to create an entrypoint and generate the configuration when starting the container

2020-11-30 14:18 UTC, tidylobster requested changes
Great job overall! Requested minor changes.

2020-11-30 14:18 UTC, tidylobster commented on .tests/models/adult/model/serving_test.yaml
> +    monitoring-model: adult_monitoring_test:27
Specifying monitoring config here to a specific model version can cause tests to fail if some previous tests were failed. Can we omit it here?

2020-11-30 14:18 UTC, tidylobster commented on .tests/models/adult/model/src/func_main.py
> +    # extracted = np.array([extract_value(kwargs[feature]) for feature in features])
Remove unnecessary comments here, they are no longer relevant.

2020-11-30 14:18 UTC, tidylobster commented on .tests/models/adult/serving.yaml
> +runtime: "hydrosphere/serving-runtime-python-3.6:0.1.2-rc0"
An old version of the runtime.

2020-11-30 14:18 UTC, tidylobster commented on .tests/models/adult/serving.yaml
> +runtime: "hydrosphere/serving-runtime-python-3.6:0.1.2-rc0"
An old version of the runtime.

2020-11-30 14:18 UTC, tidylobster commented on .tests/models/adult/serving.yaml
> +  model: adult_classification:1
Not sure if you're using this file, can we remove it?

2020-11-30 14:18 UTC, tidylobster commented on .tests/models/nyc_taxi/model/serving_test.yaml
> +    monitoring-model: nyc_taxi_monitoring_test:13
Same here with a specific monitoring model. Omit if you can.

2020-11-30 14:18 UTC, tidylobster commented on .tests/models/nyc_taxi/monitoring_model/.gitignore
> +/iforest.joblib
I don't see any dvc files, I think we can safely remove this.

2020-11-30 14:18 UTC, tidylobster commented on .tests/models/nyc_taxi/serving.yaml
> +install-command: "pip install -r requirements.txt"
An old version of the runtime.

2020-11-30 14:18 UTC, tidylobster commented on .tests/models/nyc_taxi/serving.yaml
> +  model: nyc_taxi:1
Can we remove this?

2020-11-30 14:18 UTC, tidylobster commented on .tests/utils.py
> +class ThresholdCmpOp(Enum):
Why won't you use a similar class from hydrsdk?

2020-11-30 14:18 UTC, tidylobster commented on .tests/utils.py
> +def local_monitoring_model(model):
I don't think I've seen this method being used anywhere. Is this a fixture?

2020-11-30 14:19 UTC, tidylobster commented
Another minor point — we don't need to use huge training sets for test cases. We can shrink csv files to 5-10 lines, I think.

2020-12-03 10:28 UTC, BeardedWhale commented on .tests/conftest.py
> +    sent_requests = simulate_traffic(model, predictor, demo_length=DATA_SAMPLE_SIZE)
Can you clarify this statement?

2021-04-05 12:48 UTC, KineticCookie requested changes
reject?

2021-04-05 12:53 UTC, closed without merging